"""Documents more metrics added

Revision ID: 16d029ce15c8
Revises: 80ab5042146f
Create Date: 2025-01-15 20:05:22.309485

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16d029ce15c8"
down_revision: Union[str, None] = "80ab5042146f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("revenue", sa.Float(), nullable=True))
    op.add_column("documents", sa.Column("net_profit", sa.Float(), nullable=True))
    op.add_column(
        "documents", sa.Column("revenue_growth_rate", sa.Float(), nullable=True)
    )
    op.add_column(
        "documents", sa.Column("operational_cost_reduction", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "operational_cost_reduction")
    op.drop_column("documents", "revenue_growth_rate")
    op.drop_column("documents", "net_profit")
    op.drop_column("documents", "revenue")
    # ### end Alembic commands ###
