"""Documents indexed

Revision ID: 80ab5042146f
Revises: 073c7cdeee65
Create Date: 2025-01-15 19:34:58.367129

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80ab5042146f"
down_revision: Union[str, None] = "073c7cdeee65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_documents_content_topics_conclusion",
        "documents",
        ["content", "topics", "conclusion"],
        unique=False,
        mysql_prefix="FULLTEXT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_documents_content_topics_conclusion",
        table_name="documents",
        mysql_prefix="FULLTEXT",
    )
    # ### end Alembic commands ###
